name: Deploy Licia 

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        path: project/licia-docs
    - uses: actions/checkout@v4
      with:
        repository: liriliri/licia
        path: project/licia    
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - working-directory: ./project/licia-docs
      run: |
        npm i
        npm run build 
        mkdir dist/demo        
    - working-directory: ./project/licia
      run: |
        npm i
        npm link
        licia demo
        cp -r .licia/demo/* ../licia-docs/dist/demo/
    - working-directory: ./project/licia-docs
      run: |
        mkdir -p ../../page/licia
        cp -r dist/* ../../page/licia
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "page/licia/"
        target: "/root/"    
    